#!/usr/bin/env perl

$header=0;
while (<>) {
    chomp;
    @fields = split(/\|/);
    @data = split(/,/, $fields[5]);
    if ($header == 0) {
        @hf = @fields;
        @hd = @data;
        $header++;
    } else {
        ($dummy, $nodes) = split(/=/, $fields[4]);
        if ($header < 2) {
            print "$fields[2]\n";
            $header++;
        }
        print "$fields[0] @ $nodes\n";
        for ($i = 0; $i < $#data/5; $i++) {
            print "$hd[$i*5]: $data[$i*5] $data[$i*5+1]\n";
        }
        print "\n";
    }
}
